### ISSUE TITLE
Cannot distinguish between different layouts for the same language

### ISSUE THREAD

**Issue by ablazhov** [AlexVallat/KeyLayoutAutoSwitch#3]
![KeyLayoutAutoSwitch_OneLanguageMultipleLayouts](https://user-images.githubusercontent.com/25743438/101621869-fba11580-3a1e-11eb-8227-5cfe40d8408e.png)
KeyLayoutAutoSwitch cannot distinguish between different keyboard layouts for the same language and in my case always switches to the less used one...

Please see the attached image.

**Comment by AlexVallat** [comment]
I believe this is a bug in .NET, which I've reported here: https://github.com/dotnet/winforms/issues/4345

I've got a workaround you can try, attached here, until they fix it
[KeyLayoutAutoSwitch.zip](https://github.com/AlexVallat/KeyLayoutAutoSwitch/files/5668439/KeyLayoutAutoSwitch.zip)

**Comment by ablazhov** [comment]
It works now.
Is this a universal fix or something just for my specific case with those BG layouts?

**Comment by AlexVallat** [comment]
It's not specific to Bulgarian, but I don't have complete understanding of how the windows keyboard layout registry keys work so there may be more cases it doesn't catch. If you spot any, let me know, otherwise I'll assume this works for all layouts. It would affect any case where there are more than one keyboard layout of the same language, under the same language. Hmm, terminology tricky there, but I think you get what I mean.
