### ISSUE TITLE
Better UX workflow for remembering keyboard layouts for whole sites

### ISSUE THREAD

**Issue by AlexVallat** [AlexVallat/KeyLayoutAutoSwitch#4]
(split from #2 )

**Comment by AlexVallat** [comment]
https://github.com/AlexVallat/KeyLayoutAutoSwitch/issues/2#issuecomment-740567275
Is it possible for the rule "Previously visited web page" to be available a third option "Remember current tab-set layouts" (or something along the lines) which allows KeyLayoutAutoSwitch to remember the layouts for the currently opened tabs (and change layout when tabs get activated), but to "forget" the layout of a tab when it gets closed (or the browser gets closed, too). I.e. some sort of a Volatile tab layout memory. In this case the layouts maybe should be attached to the tab-id, not the web-page URL, or at least to the site part of the URL (not the full URL). For example, stick the layout to www.yahoo.com or www.cnn.com and keep it while browsing this whole site regardless of the current html page/level/directory.

**Comment by AlexVallat** [comment]
https://github.com/AlexVallat/KeyLayoutAutoSwitch/issues/2#issuecomment-740794057
The reasons for me asking for this third option are these:
My primary language is Bulgarian. Not all bulgarian web sites are in the .bg domain. Many are registered in .com or .org or .net. I cannot possibly pick those one by one and create specific rules for them. Plus, very often I use english language even on bulgarian sites in the .bg domain.

Would it be too much to ask for this third option based on site and not on the whole URL (for example www.google.com, mail.yahoo.com, www.government.bg etc.). More often than not it would be usefull to keep the layout when clicking on links pointing to a page on the same site.
Also if it is possible to make the remembering of the layouts between browser restarts optional would be great, otherwise one could never be sure what was the layout when they last visited this site/URL.

Even if nothing of this is possible, at least it was nice to dream about it ;-)

Thanks again!

**Comment by AlexVallat** [comment]
I'm certainly interested in hearing your workflow, to try and improve this app if possible. From what I can tell, the actual switching behaviour already meets your requirements, it's just too inconvenient to create site rules. How about if there was an option for a hotkey to create a rule for the current site and keyboard layout?

So if your were on a .com site which you wanted to be in Bulgarian or a .bg site you wanted in English, then the workflow would be that, when you have a tab of that site open, you switch to they keyboard you want and then hit the hotkey. A window would open allowing you to customise the URL and language (or just accept the defaults) and a rule would be created for that site. Which would, of course, persist over browser restarts.

**Comment by AlexVallat** [comment]
https://github.com/AlexVallat/KeyLayoutAutoSwitch/issues/2#issuecomment-741695578
Find in Page works as intended now.

A hotkey (and I would suggest a tray-icon menu item) for creating site-specific rules would be very helpful!

I am filing another issue regarding situations with multiple layouts for the same Language.

**Comment by AlexVallat** [comment]
https://github.com/AlexVallat/KeyLayoutAutoSwitch/issues/2#issuecomment-742501581
A question:
Wouldn't it be usefull to have another integrated rule "Previously visited web sites", which would work just as the "Previously visited web page" rule, but based on the site and not on the entire URL? I.e. all web pages under the same site (e.g. www.google.com) should stay on the same layout (default or user-selected). Maybe those two should be made alternatively selectable (one or the other)?

I should have opened a new Issue with this topic a few posts ago...

**Comment by AlexVallat** [comment]
I want to avoid hidden rules. Setting a language for a site should be something that is visible, editable, deletable and peristable - that is what the rule system is for. Otherwise you can easily end up with a language being switched to and no idea why, or how to stop that from happening.

Working within that, and trying to find something that would fit your workflow, how about instead of a command to add a rule, there's a setting for "Auto-add rules for sites". Then, whenever you leave a page, if the keyboard layout you currently have active is not one that would already be assigned to that page by your current rules, a new rule for the site is created assigning that layout.

So, say you assign a rule to ".com" to be English, then visit mail.yahoo.com and switch to Bulgarian layout, a new rule is automatically created for mail.yahoo.com as Bulgarian. If you then go to google.com, but leave the layout as English, no new rule is created as the rule for that applies to google.com (the base .com rule) would already match the layout you use. If, at a later date, you go back to mail.yahoo.com and switch to English it would edit the mail.yahoo.com rule to be English instead of Bulgarian.

(It would be inadvisable to leave the top level "Other web pages" rule as "Don't change", though, as then a rule would be created for every new site you visit, as the current layout would always be different from the rule applied)

**Comment by ablazhov** [comment]
I can see your logic, but wouldn't it leave us with hundreds of auto- and manually created rules after a few months of browsing?
Plus it all gets too complicated and thus prone to break-downs and misbehaviours, tracking down of which would be very difficult. 
I am trying to steer KeyLayoutAutoSwitch away from creating tons of rules because:
1. The clutter - never has come anything good from (increasing) clutter  :-) - managing and searching for rules, sorting, deleting, etc...
2. When visiting English sites everything is clear - we/I use English keyboard; but visiting non-English is a different beast: Entering login credentials and e-mail addresses must be done in English, but then entering or searching for other information can be done in English OR other language. Which keyboard language/layout will be remembered and switched to the next time I visit this site? Checking every time the Windows language indicator defeates the purpose of this app. With the logic you propose we loose the deterministic switching to keyboard language/layout. I would certainly prefer ALL sites to default to English except for those I know for sure I will be using other layouts for and for those I WILL create specific rules (but those are usually rare). But if I am browsing a certain site and it so happens that I switch to non-English layout I would like this layout to become default for all pages of the entire site for this browsing session or until I switch the layout again - no hard rules created, just in Memory (temporary association of site to keyboard layout) - just like the behaviour of the integrated rule "Previously visited web pages" only for entire sites, not for specific pages. The next time I start the computer when I visit this same site I would like it to again default to English layout (because the integrated rule "Other Web Pages" will be set to English). That way I will know what layout to expect (English) when I visit this site for the first time during this browsing session and if I need to switch to a different layout it will be kept for this site until a) I switch to some other layout (which then in its turn will be kept for this site), b) computer gets restarted and all site-to-layout associations reset to English (because integrated rule "Other Web Pages" = English). 
This functionality is what I previously reffered to as "Previously visited web sites" rule. 

Maybe I miscommunicated my thoughts the previous time, but my proposal does not involve hidden rules, just temporary memory-only hashed rules which do not survive computer restarts - I believe the integrated rule "Previously visited web pages" also uses temporary memory-stored rules (associations) and do not persist after the computer restarts. Only a few static rules (kept in file Rules.xml) would need to be created for domains, sites or specific pages where I am sure I would need some non-English keyboard layout imediatelly after visiting those.

I thought It wolud be very easy to implement this funcionality being virtually the same as "Previously visited web pages" from technical point of view, only taking into account the site in the URL, not the entire URL.

**Comment by AlexVallat** [comment]
OK, I see where you're coming from. From my point of view, the clutter would still be there, still subject to break-downs and misbehaviours, and even harder to track down because the rules would all be invisible!

I do appreciate that the difference for you is that these rules would not persist through restarting the application, as they are held in memory only, so if you are restarting regularly that would serve to sweep out old rules. Unfortunately there is no good concept of a "browsing session" that I can use to clear out rules automatically.

I've decided to publish 1.2 with just the bug fixes in it, and this weekend I'll have a look again at what can be improved in this area. I will try adding a third option to "Previously visited web pages" that applies site-wide rather than to just the specific page as you suggest, and see whether it makes things too confusing in use. Perhaps a tooltip on the tray icon explaining why the language has been set the way it has would make things clear enough, and maybe a command in the tray menu to clear all memory-stored rules. Need a good name for that, though.

**Comment by ablazhov** [comment]
Is there a way to detect if the browser is no longer running? Can you use this as a hint to clear the memory-stored rules?

Such a command for manually deleting the session-history is a very good idea indeed! What about "Reset automatic rules"?

A tooltip might be a good thing but can't say before we try it. But do make it optional please so it doesn't get annoying after a while after user gets used to the layout switching logic...

**Comment by AlexVallat** [comment]
I don't think the tooltip needs to be optional, it only appears when you hover over the icon so it won't disturb at all.

Here's a build of 1.3 with the features I described in it, give it a try for a while and see whether it is confusing in actual use of if the per-site auto-remembering feels natural

[KeyLayoutAutoSwitch.zip](https://github.com/AlexVallat/KeyLayoutAutoSwitch/files/5683418/KeyLayoutAutoSwitch.zip)

**Comment by AlexVallat** [comment]
Thanks for the feedback! If the configuration window is already open then right clicking (or double clicking) the tray icon will bring the configuration window to the front.

The site rule creation command was my earlier idea for improving this workflow, but if the automatic rule per site is better then I guess that's not needed any more? Might still be nice for other use cases, though, if I get some time tomorrow I can look into it.

**Comment by ablazhov** [comment]
Nope, the config window is closed, but it opens when I right-click the tray-icon to get to the menu while Firefox is the foreground window.

"Might still be nice for other use cases, though,.." - I think it might for users who rely mainly on static (manual) rules.

**Comment by AlexVallat** [comment]
Very strange, I can't reproduce that behaviour. It shouldn't make any difference what other application was foreground, there's no code dependent on that. Weird.

**Comment by ablazhov** [comment]
> If the foreground window is Firefox then right-clicking on the tray-icon pops up the rule window simultaneously with the tray menu.
> 

Hmm, today I am not experiencing this behavior. Must have been some Microsoft glitch. Should have restarted Windows before reporting false issues...

**Comment by ablazhov** [comment]
OK, I think I narrowed it down:

If the current foreground window (any window, not just Fx) has a keyboard language/layout different than English (the default language/layout for my Windows setup) then right-clicking the tray icon of KeyLayoutAutoSwitch pops up the configuration window too. I attached a screenshot of the configuration window:

![KeyLayoutAutoSwitch_configuration](https://user-images.githubusercontent.com/25743438/102008158-2947d080-3d37-11eb-89ab-2dbb8c09c08e.png)

This is a link to a video in which I captured the whole thing (note that I used Fx for the experiment, but it happens with any other application window. I think you should be able to watch the video directly without downloading it first:
https://www.dropbox.com/s/hribt3vt1y2sm4w/MOV_0466.mp4?dl=0

**Comment by AlexVallat** [comment]
Still doesn't happen for me. Best I can tell from your video, it's counting those two right-clicks as a double-right-click. I can at least make it so that double-clicks have to be left clicks to show the config window. That, and the "Add Site Rule" command are in this build, please let me know if you are still getting the config window popping up unexpectedly.

[KeyLayoutAutoSwitch.zip](https://github.com/AlexVallat/KeyLayoutAutoSwitch/files/5684504/KeyLayoutAutoSwitch.zip)

**Comment by ablazhov** [comment]
It works fine now - no config window popping up unexpectedly.
